apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: counter-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: counter-frontend
  template:
    metadata:
      labels:
        app: counter-frontend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: counter-frontend
        image: zoddo16/counterapp-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: counter-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
