name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Image Tag
      id: tags
      run: |
        SHORT_SHA=$(git rev-parse --short=7 HEAD)
        echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "Building image: zoddo16/counterapp-ui:${SHORT_SHA}"
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Frontend Image
      run: |
        IMAGE=zoddo16/counterapp-ui
        TAG=${{ steps.tags.outputs.sha }}
        
        docker build -t ${IMAGE}:${TAG} .
        docker push ${IMAGE}:${TAG}
        
        # Also tag as main
        docker tag ${IMAGE}:${TAG} ${IMAGE}:main
        docker push ${IMAGE}:main
    
    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4
      with:
        repository: srdjanbozic/CounterApp_Infra
        path: infra
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    
    - name: Terraform Init
      run: terraform -chdir=infra init
    
    - name: Terraform Apply
      run: |
        terraform -chdir=infra apply -auto-approve \
          -var="frontend_image=zoddo16/counterapp-ui:${{ steps.tags.outputs.sha }}" \
          -var="backend_image=zoddo16/counter-backend:main"
    
    - name: Verify Deployment
      run: |
        kubectl get pods -n counterapp
        kubectl rollout status deployment/frontend-deployment -n counterapp --timeout=300s
