name: Build and Deploy Frontend

on:
  push:
    branches: [ main, dev, qa, prod ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    concurrency:
      group: frontend-${{ github.ref_name }}
      cancel-in-progress: false
    
    env:
      ENV: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
      IMAGE: zoddo16/counterapp-ui
    
    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate Image Tag
      id: tags
      run: |
        SHORT_SHA=$(git rev-parse --short=7 HEAD)
        BRANCH=${{ github.ref_name }}
        echo "sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "branch=${BRANCH}" >> $GITHUB_OUTPUT
        echo "Building: ${IMAGE}:${SHORT_SHA}"
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and Push Image
      run: |
        TAG=${{ steps.tags.outputs.sha }}
        BRANCH=${{ steps.tags.outputs.branch }}
        
        # Build and push with SHA tag
        docker build -t ${IMAGE}:${TAG} .
        docker push ${IMAGE}:${TAG}
        
        # Tag and push with env-latest
        docker tag ${IMAGE}:${TAG} ${IMAGE}:${{ env.ENV }}-latest
        docker push ${IMAGE}:${{ env.ENV }}-latest
        
        # Tag and push with branch name (backward compatibility)
        docker tag ${IMAGE}:${TAG} ${IMAGE}:${BRANCH}
        docker push ${IMAGE}:${BRANCH}
        
        echo "Pushed tags: ${TAG}, ${{ env.ENV }}-latest, ${BRANCH}"
    
    - name: Update Deployment
      run: |
        NAMESPACE=counterapp-${{ env.ENV }}
        
        # Set new image
        kubectl set image deployment/frontend-deployment \
          counter-frontend=${IMAGE}:${{ steps.tags.outputs.sha }} \
          -n ${NAMESPACE}
        
        # Wait for rollout to complete
        kubectl rollout status deployment/frontend-deployment \
          -n ${NAMESPACE} \
          --timeout=300s
    
    - name: Verify Deployment
      run: |
        NAMESPACE=counterapp-${{ env.ENV }}
        echo " Deployment completed successfully!"
        kubectl get pods -n ${NAMESPACE} -l app=counter-frontend
