name: Deploy Frontend with Terraform

on:
  push:
    branches: [ main, dev, qa, prod ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t zoddo16/counterapp-ui:${{ github.sha }} .
        docker push zoddo16/counterapp-ui:${{ github.sha }}

    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4
      with:
        repository: srdjanbozic/CounterApp_Infra
        path: infra

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Init
      run: terraform -chdir=infra init
      
    - name: Import Existing Resources to Terraform State
      run: |
        if kubectl get namespace counterapp &>/dev/null; then
          echo "Importing existing resources to Terraform state..."
          terraform -chdir=infra import kubernetes_namespace.counterapp counterapp 2>/dev/null || true
          terraform -chdir=infra import kubernetes_deployment.frontend counterapp/frontend-deployment 2>/dev/null || true
          terraform -chdir=infra import kubernetes_deployment.backend counterapp/backend-deployment 2>/dev/null || true
          terraform -chdir=infra import kubernetes_service.frontend counterapp/frontend-service 2>/dev/null || true
          terraform -chdir=infra import kubernetes_service.backend counterapp/backend-service 2>/dev/null || true
          terraform -chdir=infra import kubernetes_ingress_v1.counterapp counterapp/counter-ingress 2>/dev/null || true
          echo " Resources imported to Terraform state"
        else
          echo " No existing resources found, Terraform will create them"
        fi
          
    - name: Terraform Apply
      run: |
        terraform -chdir=infra apply -auto-approve \
          -var="frontend_image=zoddo16/counterapp-ui:${{ github.sha }}" \
          -var="backend_image=zoddo16/counter-backend:latest"
