name: Deploy Frontend with Terraform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Frontend Code
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Frontend Docker Image
      run: |
        docker build -t zoddo16/counterapp-ui:${{ github.sha }} .
        docker push zoddo16/counterapp-ui:${{ github.sha }}

    - name: Checkout Infrastructure Code
      uses: actions/checkout@v4
      with:
        repository: srdjanbozic/CounterApp_Infra
        path: infra

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      
    - name: Terraform Init
      run: terraform -chdir=infra init
      
    - name: Restore Terraform State
      run: |
        if [ -f "/home/zodd/actions-runner-frontend/_work/_temp/terraform.tfstate" ]; then
          echo "Restoring terraform state..."
          cp "/home/zodd/actions-runner-frontend/_work/_temp/terraform.tfstate" infra/terraform.tfstate
        else
          echo "No previous state found, starting fresh..."
        fi
        
    - name: Terraform Apply
      run: |
        terraform -chdir=infra apply -auto-approve \
          -var="frontend_image=zoddo16/counterapp-ui:${{ github.sha }}" \
          -var="backend_image=zoddo16/counter-backend:latest"
        
    - name: Save Terraform State  
      run: |
        echo "Saving terraform state for next run..."
        cp infra/terraform.tfstate "/home/zodd/actions-runner-frontend/_work/_temp/terraform.tfstate" || true
